services:
  - type: web
    name: satellite-mortgage-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
